Fix bug in bcrypt upgrade path
venables/has_secure_password_argon2 pull request #15
Opened 2023-11-27 21:41 UTC by venables

Fixes #14

2023-12-19 18:59 UTC, swrobel requested changes

2023-12-19 18:59 UTC, swrobel commented on lib/has_secure_password_argon2.rb
> +        self.password_digest = hash_argon2_password(unencrypted_password)
This seems like the more sensible change to me
```suggestion
        self.password = unencrypted_password
```

2024-05-09 16:20 UTC, venables commented
Thanks @swrobel !

2024-05-09 16:20 UTC, merged

2025-10-21 05:13 UTC, swrobel commented
@venables any plans to release this to Rubygems?